#docker file for nodejs and postgresql
services:
  backend:
    image: node:latest
    container_name: IV1201_backend
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - database
    environment:
      BACKEND_PORT: $BACKEND_PORT
      DATABASE_URL: $DATABASE_URL
  database:
    image: postgres:alpine
    container_name: IV1201_postgres
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB

volumes:
  pgdata:
